### ISSUE TITLE
Only the last tag considered

### ISSUE THREAD

**Issue by tlvince** [fcpg/vim-waikiki#4]
Given the following file:

```md
# Index

:foo:bar:
```

... the resulting tags file is generated:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
bar	index.md	/^:foo:bar:$/;"	t	language:waikiki
```

... i.e. only the `bar` tag exists.

```
:tags
  # TO tag         FROM line  in file/text
  1  1 bar                 1  # Hello
```

I'd expected both `foo` and `bar` to exist.

vim-waikiki cd29dbe1a2485be2ca4e51341481defa8adace35

**Comment by fcpg** [comment]
Right, thanks for reporting it. I just pushed a patch, let me know if it works, so that I can start changing the docs. 
New limitation is that not more that six tags are supported, and it's going to be more cumbersome to customize for users if need be.

**Comment by tlvince** [comment]
Yep, works 👍

Shame the regex has ballooned though. Maybe there's another way to do it?

**Comment by fcpg** [comment]
Due to the lack of lookarounds, ctags doesn't seem to be able to deal with repetitions on a single line, unless each element can be matched individually without any context at all (which would mean some special markup for each tag).

If I keep it as is, I probably won't expose the tag-matching regexp anymore in the options, but replace it with a few moving parts eg. configurable start-of-tag-list, end-of-tag-list and separator options (all defaulting to ':'). Another advantage of the current solution is that I can check tags are a on line on their own, so ctags won't match bad tags by mistake (eg. some asciidoc options...).
